language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw=dev
    - gcc
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  cp config/rusty.toml ~/.rusty.toml
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success:
- travis-cargo coveralls --no-sudo
- travis-cargo --only nightly doc-upload
- bash <(curl -s https://codecov.io/bash) \
   -t b11d2bed-4f53-42be-aac4-6c82f5728b9e
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: J00Y1GjyrcOuacsvXQjxtQJmigM63tj9NWa80UQ426pQHyL964ZV1K15egDO6a70j4fffl1cunKxzCkdLaR/3PKB4FCcqum3nmNLuCTFrfCHSgmf58cQXPWFC1Btuqy9Z3C3qzUXw2xhyRlHph1Nl80uinJ4F+Ae71Htwy0iTwAmRGiOwfm2Mrnuz+vuoClwVG3jkHcfJ5ZDkHJWVWtQ4IJR/i3kuLSyN5VK1RpR/T3T1PLaurgDWN3o2Hufbqny6PJEHq6jJ92gRB7Th69nBppFJrJe3fSy9I/MyBK5W6xeVAdYCIu2K6oeTtBVWugTZHBN6e/hwdtK6VppfppxV2EhEYfUD7e2pNOmOV/MJ5N2bAs0pGhp547c7NICbJqvVRq7oOhay8zX3BGjtwBaGEpGeGYRmYoo8/cRI2B4DnmgFOQuZiNTiyCficvteWmEhO2YY527vu3ujjWhnDpzWsvuTAxJTVDBqTmDVhf8hlUiBTzggk/ayAxVKr699AvjZopeHVlyET789nOS0bok0sS3WJ+kz0LrKI2RB5bAKCckx7thEVLwLlVvZQzlRwksWVd/u7hcXtfJeiMygCglp1nh7NtaaydELmmI5fwF1x14BF9VPeiAqElYzig1rvyBmMIXp7TrzhbaqORubBCnqm5ugwpUYYG4xoplcKcMlAs=
